# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: "^.flakeheaven_cache/.*$"
      - id: forbid-submodules
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: ['toml']
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.3.0
    hooks:
      - id: flakeheaven
#    hooks:
#    -   id: flakehell
#        name: flakehell (flake8 wrapper)
#        description: flake8 wrapper for pyproject.toml compat
#        entry: flakehell
#        args: ['lint']
#        language: python
#        types: [python]
#-   repo: https://github.com/pycqa/flake8
#    rev: 4.0.1
#    hooks:
#    -    id: flake8
#         exclude: ^samples/
