# https://cjolowicz.github.io/posts/hypermodern-python-06-ci-cd/
name: Release Drafter
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
